-- Migración: Asegurar VARCHAR(20) para columnas de placa en DeteccionVehiculo
IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DeteccionVehiculo' AND COLUMN_NAME = 'placa' AND CHARACTER_MAXIMUM_LENGTH < 20)
BEGIN
    ALTER TABLE DeteccionVehiculo ALTER COLUMN placa VARCHAR(20) NULL;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DeteccionVehiculo' AND COLUMN_NAME = 'placa_reconocida' AND CHARACTER_MAXIMUM_LENGTH < 20)
BEGIN
    ALTER TABLE DeteccionVehiculo ALTER COLUMN placa_reconocida VARCHAR(20) NULL;
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'DeteccionVehiculo' AND COLUMN_NAME = 'placa_validada' AND CHARACTER_MAXIMUM_LENGTH < 20)
BEGIN
    ALTER TABLE DeteccionVehiculo ALTER COLUMN placa_validada VARCHAR(20) NULL;
END
GO
